### ISSUE TITLE
Example Problems UndefVarError: C not defined

### ISSUE THREAD

**Issue by Liberty009** [ichatzinikolaidis/CasADi.jl#4]
Hi, 

Thanks for developing this it looks very useful.

I've just got it installed and tried to test it with the examples you've supplied but once I get to either the `f = (α - x)^2 + b*(y - x^2)^2` line in Create NLP Solver or `opti.minimize( (y - x^2)^2 )` in Using Opti Stack, I get an error `UndefVarError: C not defined`, from Line 12 in mathops.jl

I'm assuming I've got something setup wrong, if you could help that would be great.

Thanks!

**Comment by ichatzinikolaidis** [comment]
Hi, I run the examples without problems but there is certainly a case that I configured sth wrongly 🤔... Which Julia version do you use? Do you use a manually installed version of casadi or the one automatically downloaded from conda?

**Comment by Liberty009** [comment]
Hi,

I'm using Julia 1.5.3 with the miniconda and casadi that are automatically installed. 

Thanks!

**Comment by Liberty009** [comment]
Hi,

Having looked a bit more at it, it seems that it's only a problem with the multiplication section of the file.

Thanks!

**Comment by ichatzinikolaidis** [comment]
Hi @Liberty009, sorry for the late reply! I believe 704a1b5197270eb1f0d40becea0503759d57ef35 fixes the issue :smiley:
